defaultFont = "Inter"
monospaced.font = "JetBrains Mono"

Component.arc = 8
Button.arc = 8
CheckBox.arc = 4
ProgressBar.arc = 6
Component.arrowType = chevron

ScrollBar.width = 11
ScrollBar.thumbArc = 999
ScrollBar.thumbInsets = 2,2,2,2
ScrollBar.showButtons = false

Table.showHorizontalLines = false
Table.showVerticalLines = false
Table.intercellSpacing = 0,0
Table.rowHeight = 22
Table.cellMargins = 1,6,1,6
[light]Table.alternateRowColor = darken($Table.background,3%)
[dark]Table.alternateRowColor = lighten($Table.background,4%)
TableHeader.height = 24
TableHeader.separatorColor = $TableHeader.background

Tree.rowHeight = 22
Tree.selectionArc = 8
Tree.selectionInsets = 0,4,1,4
List.cellHeight = 22
List.selectionArc = 8
List.selectionInsets = 0,4,1,4

TabbedPane.tabType = underlined
TabbedPane.showTabSeparators = false
TabbedPane.tabHeight = 30
TabbedPane.tabInsets = 4,12,4,12

TitlePane.unifiedBackground = true

ModernDocking.overlayBackground = fade($Component.focusColor,30%)
[light]ModernDocking.headerBackground = darken($Panel.background,4%)
[dark]ModernDocking.headerBackground = lighten($Panel.background,5%)
